server:
  port: 8002

spring:
  application:
    name: sharding-storage-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: koinpay

      config:
        namespace: koinpay
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        refresh-enabled: true
        #手动设置默认dataId名称无需按nacos默认配置文件方式构造dataId
        name: account.yml
        file-extension: yaml